// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcqD8xtYUdTGkMwDS9qEoW-KG44Zm6W1I',
    appId: '1:451056813120:web:e2d0141764fcebabd9cba5',
    messagingSenderId: '451056813120',
    projectId: 'prohourassignment',
    authDomain: 'prohourassignment.firebaseapp.com',
    storageBucket: 'prohourassignment.appspot.com',
    measurementId: 'G-0293HQ35YD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNWlTTQp5mXoq1kOmZn4sm1Qsq4la8VF8',
    appId: '1:451056813120:android:efabb6dbbdc03b5fd9cba5',
    messagingSenderId: '451056813120',
    projectId: 'prohourassignment',
    storageBucket: 'prohourassignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlmDdLbyxAwkhO_nzPhNymf63Tt4X4-BY',
    appId: '1:451056813120:ios:89454229b0c9cabcd9cba5',
    messagingSenderId: '451056813120',
    projectId: 'prohourassignment',
    storageBucket: 'prohourassignment.appspot.com',
    iosBundleId: 'com.example.prhourassign',
  );
}
